[project]
name = "devlens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "python-dotenv>=1.1.1",
    "questionary>=2.1.1",
    "requests>=2.32.5",
    "rich>=14.1.0",
    "typer>=0.17.4",
]
