[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "devlens"
version = "0.1.0"
description = "Test CLI"
dependencies = [
    { file = "requirements.txt" }
]

[project.scripts]
devlens = "devlens.cli:app"
